import React,{useCallback,useEffect,useState}from"react";
import{Icon}from"@iconify/react/dist/iconify.js";
import{toast}from"react-toastify";
import{deleteFranchiseBusinessProjection,listActiveFranchises,listFranchiseBusinessProjections,listFranchisePlans,listFranchiseRegistrations}from"../../../lib/api/adminApi";
import{ApiError}from"../../../lib/api/client";
import FormModal from"../../../components/admin/FormModal";
import{exportCsv,formatInr,PAGE_SIZE,statusBadge}from"../franchiseShared";
import FranchiseProjectionFormLayer from"./FranchiseProjectionFormLayer";

export default function FranchiseProjectionListLayer(){
 const[items,setItems]=useState([]),[registrations,setRegistrations]=useState([]),[franchises,setFranchises]=useState([]),[plans,setPlans]=useState([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[status,setStatus]=useState(""),[q,setQ]=useState(""),[loading,setLoading]=useState(true),[modal,setModal]=useState(null);
 const load=useCallback(async()=>{setLoading(true);try{const[result,regResult,franchiseResult,planResult]=await Promise.all([listFranchiseBusinessProjections({status:status||undefined,q:q||undefined,limit:PAGE_SIZE,offset:(page-1)*PAGE_SIZE}),listFranchiseRegistrations({status:"all",limit:100,offset:0}),listActiveFranchises({status:"all",limit:100,offset:0}),listFranchisePlans({includeInactive:true,limit:100,offset:0})]);setItems(result.items||[]);setTotal(result.total||0);setRegistrations(regResult.items||[]);setFranchises(franchiseResult.items||[]);setPlans(planResult.items||[]);}catch(error){toast.error(error instanceof ApiError?error.message:String(error));}finally{setLoading(false);}},[status,q,page]);
 useEffect(()=>{load();},[load]);
 const remove=async(item)=>{if(!window.confirm("Delete this projection?"))return;try{await deleteFranchiseBusinessProjection(item.id);toast.success("Projection deleted.");load();}catch(error){toast.error(error instanceof ApiError?error.message:String(error));}};
 return <><div className='mb-20 d-flex justify-content-between align-items-start'><div><h3 className='fw-bold mb-4'>Business Projections</h3><p className='text-secondary-light'>Configure territory-level financial projections for franchise partners.</p></div><button className='btn btn-primary' onClick={()=>setModal({mode:"add"})}><Icon icon='mdi:plus'/> Add Projection</button></div>
 <div className='card radius-12'><div className='card-body p-24'><div className='p4u-admin-filter-row gap-8 mb-20'><input className='form-control' style={{maxWidth:420}} placeholder='Search territory, city, state...' value={q} onChange={(e)=>setQ(e.target.value)}/><select className='form-select w-auto' value={status} onChange={(e)=>setStatus(e.target.value)}><option value=''>All statuses</option><option value='draft'>Draft</option><option value='submitted'>Submitted</option><option value='approved'>Approved</option><option value='rejected'>Rejected</option></select><div className='p4u-admin-filter-row__end'><button className='btn btn-outline-secondary' onClick={()=>exportCsv("franchise-projections",["Territory","City","State","Initial Investment","Fee","Monthly Revenue","Annual Revenue","Break Even","ROI","Status"],items.map((x)=>[x.territoryName,x.city,x.state,x.initialInvestment,x.franchiseFee,x.projectedMonthlyRevenue,x.projectedAnnualRevenue,x.projectedBreakEvenMonths,x.projectedRoiPercent,x.status]))}>Export CSV</button></div></div>
 <div className='table-responsive'><table className='table bordered-table align-middle text-nowrap'><thead><tr><th>TERRITORY</th><th>CITY / STATE</th><th>PLAN</th><th>INITIAL INVESTMENT</th><th>FRANCHISE FEE</th><th>MONTHLY REVENUE</th><th>ANNUAL REVENUE</th><th>BREAK-EVEN</th><th>ROI %</th><th>STATUS</th><th>PREPARED BY</th><th>ACTIONS</th></tr></thead><tbody>{loading?<tr><td colSpan='12' className='text-center'>Loading...</td></tr>:!items.length?<tr><td colSpan='12' className='text-center'>No projections found.</td></tr>:items.map((item)=><tr key={item.id}><td><strong>{item.territoryName}</strong></td><td>{item.city||"—"} / {item.state||"—"}</td><td>{item.planName||"—"}</td><td>{formatInr(item.initialInvestment)}</td><td>{formatInr(item.franchiseFee)}</td><td>{formatInr(item.projectedMonthlyRevenue)}</td><td>{formatInr(item.projectedAnnualRevenue)}</td><td>{item.projectedBreakEvenMonths??"—"} months</td><td>{item.projectedRoiPercent??"—"}%</td><td><span className={`px-10 py-4 rounded-pill ${statusBadge(item.status)}`}>{item.status}</span></td><td>{item.preparedBy||"—"}</td><td><button className='btn btn-sm btn-outline-primary me-4' onClick={()=>setModal({mode:"view",item})}>View</button><button className='btn btn-sm btn-outline-success me-4' onClick={()=>setModal({mode:"edit",item})}>Edit</button><button className='btn btn-sm btn-outline-danger' onClick={()=>remove(item)}>Delete</button></td></tr>)}</tbody></table></div>
 <div className='d-flex justify-content-between'><span>Showing {items.length?(page-1)*PAGE_SIZE+1:0}–{Math.min(page*PAGE_SIZE,total)} of {total}</span><div><button className='btn btn-sm btn-light me-4' disabled={page===1} onClick={()=>setPage(page-1)}>Previous</button><button className='btn btn-sm btn-light' disabled={page*PAGE_SIZE>=total} onClick={()=>setPage(page+1)}>Next</button></div></div>
 </div></div>{modal&&<FormModal size='xl' onClose={()=>setModal(null)}><FranchiseProjectionFormLayer initialData={modal.item} isEdit={modal.mode==="edit"} isView={modal.mode==="view"} registrations={registrations} franchises={franchises} plans={plans} onCancel={()=>setModal(null)} onSuccess={()=>{setModal(null);load();}}/></FormModal>}</>;
}
