import React, { useCallback, useEffect, useState } from "react";
import { Icon } from "@iconify/react/dist/iconify.js";
import { toast } from "react-toastify";
import {
  createFoodCoupon, createFoodRestaurant, createFoodRider, deleteFoodCoupon, deleteFoodRestaurant, deleteFoodRider,
  listFoodCoupons, listFoodOrders, listFoodRestaurants, listFoodRiderSettlements, listFoodRiders, payFoodRiderSettlement,
  updateFoodCoupon, updateFoodOrder, updateFoodRestaurant, updateFoodRider, updateFoodRiderKyc,
} from "../../lib/api/adminApi";
import { ApiError } from "../../lib/api/client";

const CONFIG = {
  restaurants: { title: "Restaurants", subtitle: "restaurants on the platform", add: "Add Restaurant", empty: "No restaurants yet." },
  riders: { title: "Riders", subtitle: "riders", add: "Add Rider", empty: "No riders yet." },
  kyc: { title: "Rider KYC Review", subtitle: "Approve or reject rider documents", empty: "No riders here." },
  settlements: { title: "Rider Settlements", subtitle: "Pay riders for completed deliveries", empty: "No pending payouts." },
  orders: { title: "Food Orders", subtitle: "orders", empty: "No food orders yet." },
  coupons: { title: "Food Coupons", subtitle: "promo codes for the food vertical", add: "New Coupon", empty: "No coupons yet." },
};
function errorMessage(e) { return e instanceof ApiError ? e.message : String(e?.message || e || "Something went wrong"); }
function Toggle({ checked, onChange, label }) { return <label className='p4u-food-switch'><input type='checkbox' checked={checked} onChange={(e) => onChange(e.target.checked)} /><span />{label}</label>; }
function money(v) { return Number(v || 0).toLocaleString("en-IN", { maximumFractionDigits: 0 }); }
function Field({ form, set, name, label, ...props }) { return <label><span>{label}</span><input value={form[name] ?? ""} onChange={(e) => set(name, e.target.value)} {...props} /></label>; }

function Modal({ module, initial, onClose, onSave }) {
  const [form, setForm] = useState(initial || {});
  const set = (k, v) => setForm((p) => ({ ...p, [k]: v }));
  const field = (name, label, props = {}) => <Field form={form} set={set} name={name} label={label} {...props} />;
  return <div className='p4u-food-modal-backdrop' role='presentation' onClick={onClose}><section className='p4u-food-modal' onClick={(e) => e.stopPropagation()}><button className='p4u-food-close' onClick={onClose}><Icon icon='mdi:close' /></button><h2>{module === "restaurants" ? "New Restaurant" : module === "riders" ? "New Rider" : module === "coupons" ? "New Coupon" : "Edit"}</h2><div className='p4u-food-form'>
    {module === "restaurants" ? <>{field("title", "Name *", { autoFocus: true })}{field("tagline", "Tagline")}<label><span>Description</span><textarea value={form.description || ""} onChange={(e) => set("description", e.target.value)} /></label>{field("cuisines", "Cuisine (comma-separated)", { placeholder: "Cuisine names" })}{field("address", "Address *")}<div className='p4u-food-grid'>{field("latitude", "Latitude")}{field("longitude", "Longitude")}{field("phone", "Phone")}{field("vendorId", "Vendor ID (link)")}{field("coverImageUrl", "Cover Image URL")}{field("bannerUrl", "Banner URL")}</div>{field("logoUrl", "Logo URL")}{field("galleryUrls", "Gallery URLs (comma-separated)")}<div className='p4u-food-grid'>{field("fssaiLicense", "FSSAI License")}{field("openingTime", "Opening Time", { type: "time" })}{field("closingTime", "Closing Time", { type: "time" })}{field("avgPrepMin", "Avg Prep Min", { placeholder: "Minutes" })}{field("deliveryRadiusKm", "Delivery Radius (km)", { placeholder: "Kilometers" })}{field("packagingFee", "Packaging Fee ₹", { placeholder: "Amount" })}{field("minOrder", "Min Order ₹", { placeholder: "Amount" })}{field("commissionPercent", "Commission %", { placeholder: "Minutes" })}</div><div className='p4u-food-toggle-row'><Toggle checked={!!form.isPureVeg} onChange={(v) => set("isPureVeg", v)} label='Pure Veg' /><Toggle checked={form.isActive !== false} onChange={(v) => set("isActive", v)} label='Active' /></div></> : null}
    {module === "riders" ? <>{field("name", "Name", { autoFocus: true })}{field("mobile", "Mobile")}{field("email", "Email")}<div className='p4u-food-grid'><label><span>Vehicle</span><select value={form.vehicleType || "Bike"} onChange={(e) => set("vehicleType", e.target.value)}><option>Bike</option><option>Scooter</option><option>Cycle</option><option>Car</option></select></label>{field("vehicleNo", "Vehicle No.")}</div></> : null}
    {module === "coupons" ? <>{field("code", "Code *", { autoFocus: true, placeholder: "Coupon code" })}{field("title", "Title *", { placeholder: "Coupon title" })}<label><span>Description</span><textarea value={form.description || ""} onChange={(e) => set("description", e.target.value)} /></label><div className='p4u-food-grid'><label><span>Discount Type</span><select value={form.discountType || "flat"} onChange={(e) => set("discountType", e.target.value)}><option value='flat'>Flat ₹</option><option value='percent'>Percent %</option></select></label>{field("discountValue", "Discount Value *", { placeholder: "Value" })}{field("maxDiscount", "Max Discount ₹ (for %)")}{field("minOrder", "Min Order ₹", { placeholder: "Amount" })}{field("perCustomerLimit", "Per-Customer Limit", { placeholder: "Limit" })}{field("totalUsageLimit", "Total Usage Limit")}</div><Toggle checked={form.platformWide !== false} onChange={(v) => set("platformWide", v)} label='Platform-wide (all restaurants)' /><div className='p4u-food-grid'>{field("startsAt", "Starts", { type: "datetime-local" })}{field("expiresAt", "Expires", { type: "datetime-local" })}</div><Toggle checked={form.isActive !== false} onChange={(v) => set("isActive", v)} label='Active' /></> : null}
    <div className='p4u-food-modal-actions'><button type='button' className='is-cancel' onClick={onClose}>Cancel</button><button type='button' className='is-save' onClick={() => onSave(form)}>Save</button></div></div></section></div>;
}

export default function FoodModuleLayer({ module }) {
  const cfg = CONFIG[module];
  const [items, setItems] = useState([]);
  const [tab, setTab] = useState("pending");
  const [modal, setModal] = useState(null);
  const listFn = module === "restaurants" ? listFoodRestaurants : module === "riders" || module === "kyc" ? listFoodRiders : module === "settlements" ? listFoodRiderSettlements : module === "orders" ? listFoodOrders : listFoodCoupons;
  const load = useCallback(async () => { try { const status = module === "kyc" ? tab : module === "settlements" ? (tab === "history" ? "paid" : "pending") : undefined; const res = await listFn({ includeInactive: true, status, limit: 500, offset: 0 }); setItems(res.items || []); } catch (e) { toast.error(errorMessage(e)); setItems([]); } }, [listFn, module, tab]);
  useEffect(() => { void load(); }, [load]);
  const countText = module === "kyc" || module === "settlements" ? cfg.subtitle : `${items.length} ${cfg.subtitle}`;
  const save = async (body) => { try { if (module === "restaurants") body.id ? await updateFoodRestaurant(body.id, body) : await createFoodRestaurant(body); if (module === "riders") body.id ? await updateFoodRider(body.id, body) : await createFoodRider(body); if (module === "coupons") body.id ? await updateFoodCoupon(body.id, body) : await createFoodCoupon(body); toast.success("Saved."); setModal(null); await load(); } catch (e) { toast.error(errorMessage(e)); } };
  const remove = async (item) => { try { if (module === "restaurants") await deleteFoodRestaurant(item.id); if (module === "riders") await deleteFoodRider(item.id); if (module === "coupons") await deleteFoodCoupon(item.id); toast.success("Deleted."); await load(); } catch (e) { toast.error(errorMessage(e)); } };
  const approveKyc = async (id, status) => { try { await updateFoodRiderKyc(id, status); await load(); } catch (e) { toast.error(errorMessage(e)); } };
  const pay = async (id) => { try { await payFoodRiderSettlement(id); await load(); } catch (e) { toast.error(errorMessage(e)); } };
  return <div className='p4u-food-page'><div className='p4u-food-head'><div><h1>{cfg.title}</h1><p>{countText}</p></div>{cfg.add ? <button onClick={() => setModal({ isActive: true, platformWide: true })}><Icon icon='mdi:plus' />{cfg.add}</button> : null}</div>{module === "kyc" ? <div className='p4u-food-tabs'>{["pending", "verified", "rejected"].map((x) => <button className={tab === x ? "active" : ""} onClick={() => setTab(x)} key={x}>{x[0].toUpperCase()+x.slice(1)} ({items.length})</button>)}</div> : null}{module === "settlements" ? <div className='p4u-food-tabs'><button className={tab === "pending" ? "active" : ""} onClick={() => setTab("pending")}>Pending Balances ({items.length})</button><button className={tab === "history" ? "active" : ""} onClick={() => setTab("history")}>History ({items.length})</button></div> : null}{items.length === 0 ? <div className='p4u-food-empty'>{cfg.empty}</div> : <section className='p4u-food-list'>{items.map((item) => <article key={item.id}><div><strong>{item.title || item.name || item.code || item.orderNo || item.riderName}</strong><span>{item.address || item.mobile || item.title || item.restaurantName || `₹${money(item.amount || item.total || item.discountValue)}`}</span></div><div>{module === "kyc" ? <><button onClick={() => approveKyc(item.id, "verified")}>Approve</button><button className='danger' onClick={() => approveKyc(item.id, "rejected")}>Reject</button></> : null}{module === "settlements" && item.status === "pending" ? <button onClick={() => pay(item.id)}>Pay</button> : null}{["restaurants", "riders", "coupons"].includes(module) ? <><button onClick={() => setModal(item)}>Edit</button><button className='danger' onClick={() => remove(item)}>Delete</button></> : null}{module === "orders" ? <button onClick={() => updateFoodOrder(item.id, { status: "completed" }).then(load)}>Complete</button> : null}</div></article>)}</section>}{modal ? <Modal module={module} initial={modal} onClose={() => setModal(null)} onSave={save} /> : null}</div>;
}
