import React,{useCallback,useEffect,useState}from"react";
import{toast}from"react-toastify";
import{listActiveFranchises,listFranchisePlans,suspendActiveFranchise,terminateActiveFranchise}from"../../../lib/api/adminApi";
import{ApiError}from"../../../lib/api/client";
import FormModal from"../../../components/admin/FormModal";
import{exportCsv,formatDate,formatInr,PAGE_SIZE,statusBadge}from"../franchiseShared";
import ActiveFranchiseFormLayer from"./ActiveFranchiseFormLayer";

export default function ActiveFranchiseListLayer(){
 const[items,setItems]=useState([]),[plans,setPlans]=useState([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[status,setStatus]=useState("active"),[planId,setPlanId]=useState(""),[paymentStatus,setPaymentStatus]=useState(""),[q,setQ]=useState(""),[state,setState]=useState(""),[city,setCity]=useState(""),[loading,setLoading]=useState(true),[modal,setModal]=useState(null);
 const load=useCallback(async()=>{setLoading(true);try{const[result,planResult]=await Promise.all([listActiveFranchises({status,planId:planId||undefined,q:q||undefined,paymentStatus:paymentStatus||undefined,state:state||undefined,city:city||undefined,limit:PAGE_SIZE,offset:(page-1)*PAGE_SIZE}),listFranchisePlans({includeInactive:true,limit:100,offset:0})]);setItems(result.items||[]);setTotal(result.total||0);setPlans(planResult.items||[]);}catch(error){toast.error(error instanceof ApiError?error.message:String(error));}finally{setLoading(false);}},[status,planId,paymentStatus,q,state,city,page]);
 useEffect(()=>{load();},[load]);
 const action=async(item,type)=>{if(!window.confirm(`${type==="suspend"?"Suspend":"Terminate"} ${item.franchiseCode}?`))return;try{if(type==="suspend")await suspendActiveFranchise(item.id);else await terminateActiveFranchise(item.id);toast.success("Franchise status updated.");load();}catch(error){toast.error(error instanceof ApiError?error.message:String(error));}};
 return <><div className='mb-20'><h3 className='fw-bold mb-4'>Active Franchises</h3><p className='text-secondary-light'>Manage lifecycle, payments, and receipts of live franchise partners.</p></div>
 <div className='card radius-12 mb-20'><div className='card-body'><h5>Search & filters</h5><div className='row g-12'><Filter><select className='form-select' value={planId} onChange={(e)=>setPlanId(e.target.value)}><option value=''>All Plans</option>{plans.map((plan)=><option key={plan.id} value={plan.id}>{plan.planName}</option>)}</select></Filter><Filter><select className='form-select' value={status} onChange={(e)=>setStatus(e.target.value)}><option value='active'>Active</option><option value='suspended'>Suspended</option><option value='terminated'>Terminated</option><option value='all'>All</option></select></Filter><Filter><select className='form-select' value={paymentStatus} onChange={(e)=>setPaymentStatus(e.target.value)}><option value=''>All payments</option><option value='paid'>Paid</option><option value='pending'>Pending</option><option value='unpaid'>Unpaid</option><option value='refunded'>Refunded</option></select></Filter><Filter><input className='form-control' placeholder='Search state' value={state} onChange={(e)=>setState(e.target.value)}/></Filter><Filter><input className='form-control' placeholder='Search city' value={city} onChange={(e)=>setCity(e.target.value)}/></Filter><Filter><input className='form-control' placeholder='Mobile / Email / Name' value={q} onChange={(e)=>setQ(e.target.value)}/></Filter></div></div></div>
 <div className='card radius-12'><div className='card-body p-24'><div className='d-flex justify-content-between mb-20'><input className='form-control' style={{maxWidth:420}} placeholder='Search...' value={q} onChange={(e)=>setQ(e.target.value)}/><button className='btn btn-outline-secondary' onClick={()=>exportCsv("active-franchises",["Code","Owner","Business","Plan","State","Territory","Paid","Status"],items.map((x)=>[x.franchiseCode,x.ownerName,x.businessName,x.planName,x.state,x.territoryDescription,x.paymentStatus,x.status]))}>Export CSV</button></div>
 <div className='table-responsive'><table className='table bordered-table align-middle text-nowrap'><thead><tr><th>FRANCHISE ID</th><th>OWNER</th><th>COMPANY</th><th>PLAN</th><th>CITY / STATE</th><th>TERRITORY</th><th>PLAN DATES</th><th>PAYMENT</th><th>ROYALTY</th><th>STATUS</th><th>ACTIONS</th></tr></thead><tbody>{loading?<tr><td colSpan='11' className='text-center'>Loading...</td></tr>:!items.length?<tr><td colSpan='11' className='text-center'>No franchises found.</td></tr>:items.map((item)=><tr key={item.id}><td><strong>{item.franchiseCode}</strong></td><td>{item.ownerName}<div className='text-xs'>{item.phone}</div></td><td>{item.businessName||"—"}</td><td>{item.planName||"—"}</td><td>{item.city||"—"} / {item.state||"—"}</td><td>{item.territoryDescription||"—"}</td><td>{formatDate(item.planStartDate)} – {formatDate(item.planEndDate)}</td><td><span className={`px-10 py-4 rounded-pill ${statusBadge(item.paymentStatus)}`}>{item.paymentStatus}</span></td><td>{item.royaltyPercent}%</td><td><span className={`px-10 py-4 rounded-pill ${statusBadge(item.status)}`}>{item.status}</span></td><td><button className='btn btn-sm btn-outline-primary me-4' onClick={()=>setModal({mode:"view",item})}>View</button><button className='btn btn-sm btn-outline-success me-4' onClick={()=>setModal({mode:"edit",item})}>Edit</button>{item.status==="active"&&<button className='btn btn-sm btn-warning me-4' onClick={()=>action(item,"suspend")}>Suspend</button>}{item.status!=="terminated"&&<button className='btn btn-sm btn-danger' onClick={()=>action(item,"terminate")}>Terminate</button>}</td></tr>)}</tbody></table></div>
 <div className='d-flex justify-content-between'><span>Showing {items.length?(page-1)*PAGE_SIZE+1:0}–{Math.min(page*PAGE_SIZE,total)} of {total}</span><div><button className='btn btn-sm btn-light me-4' disabled={page===1} onClick={()=>setPage(page-1)}>Previous</button><button className='btn btn-sm btn-light' disabled={page*PAGE_SIZE>=total} onClick={()=>setPage(page+1)}>Next</button></div></div>
 </div></div>{modal&&<FormModal size='lg' onClose={()=>setModal(null)}><ActiveFranchiseFormLayer initialData={modal.item} isView={modal.mode==="view"} onCancel={()=>setModal(null)} onSuccess={()=>{setModal(null);load();}}/></FormModal>}</>;
}
const Filter=({children})=><div className='col-md'>{children}</div>;
