import React,{useCallback,useEffect,useMemo,useState}from"react";
import{Icon}from"@iconify/react/dist/iconify.js";
import{toast}from"react-toastify";
import{listFranchiseRegistrationPayments,listFranchiseRegistrations,updateFranchiseRegistrationPayment}from"../../../lib/api/adminApi";
import{ApiError}from"../../../lib/api/client";
import FormModal from"../../../components/admin/FormModal";
import{exportCsv,formatDate,formatInr,PAGE_SIZE,statusBadge}from"../franchiseShared";
import FranchisePaymentFormLayer from"./FranchisePaymentFormLayer";

export default function FranchisePaymentListLayer(){
 const[items,setItems]=useState([]),[registrations,setRegistrations]=useState([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[status,setStatus]=useState(""),[q,setQ]=useState(""),[dateFrom,setDateFrom]=useState(""),[dateTo,setDateTo]=useState(""),[loading,setLoading]=useState(true),[modal,setModal]=useState(null);
 const load=useCallback(async()=>{setLoading(true);try{const[result,registrationResult]=await Promise.all([listFranchiseRegistrationPayments({status:status||undefined,q:q||undefined,dateFrom:dateFrom||undefined,dateTo:dateTo||undefined,limit:PAGE_SIZE,offset:(page-1)*PAGE_SIZE}),listFranchiseRegistrations({status:"all",limit:100,offset:0})]);setItems(result.items||[]);setTotal(result.total||0);setRegistrations(registrationResult.items||[]);}catch(error){toast.error(error instanceof ApiError?error.message:String(error));}finally{setLoading(false);}},[status,q,dateFrom,dateTo,page]);
 useEffect(()=>{load();},[load]);
 const summary=useMemo(()=>({collected:items.filter((x)=>x.paymentStatus==="success").reduce((sum,x)=>sum+Number(x.amount),0),pending:items.filter((x)=>x.paymentStatus==="pending").reduce((sum,x)=>sum+Number(x.amount),0),entities:new Set(items.map((x)=>x.registrationId)).size}),[items]);
 const updateStatus=async(item,paymentStatus)=>{if(!window.confirm(`Mark this payment as ${paymentStatus}?`))return;try{await updateFranchiseRegistrationPayment(item.id,{paymentStatus});toast.success("Payment updated.");load();}catch(error){toast.error(error instanceof ApiError?error.message:String(error));}};
 return <><div className='mb-20'><h3 className='fw-bold mb-4'>Registration Payments</h3><p className='text-secondary-light'>Centralized ledger of all franchise registration payments</p></div>
 <div className='row g-12 mb-20'><Card title='Payments on page' value={items.length}/><Card title='Amount Collected' value={formatInr(summary.collected)}/><Card title='Pending Amount' value={formatInr(summary.pending)}/><Card title='Unique Registrations' value={summary.entities}/></div>
 <div className='card radius-12'><div className='card-body p-24'><div className='p4u-admin-filter-row gap-8 mb-20'><input className='form-control' style={{maxWidth:400}} placeholder='Search receipt, registration, UTR...' value={q} onChange={(e)=>setQ(e.target.value)}/><input type='date' className='form-control w-auto' value={dateFrom} onChange={(e)=>setDateFrom(e.target.value)}/><input type='date' className='form-control w-auto' value={dateTo} onChange={(e)=>setDateTo(e.target.value)}/><select className='form-select w-auto' value={status} onChange={(e)=>setStatus(e.target.value)}><option value=''>All</option><option value='pending'>Pending</option><option value='success'>Paid</option><option value='failed'>Failed</option><option value='refunded'>Refunded</option></select><div className='p4u-admin-filter-row__end d-flex gap-8'><button className='btn btn-outline-secondary' onClick={()=>exportCsv("franchise-payments",["Payment ID","Registration","Applicant","Plan","Amount","Mode","Status","Transaction","Paid At"],items.map((x)=>[x.id,x.registrationId,x.applicantName,x.planName,x.amount,x.paymentMode,x.paymentStatus,x.transactionId,x.paidAt]))}><Icon icon='mdi:download-outline'/> CSV</button><button className='btn btn-primary' onClick={()=>setModal({mode:"add"})}><Icon icon='mdi:plus'/> Record Payment</button></div></div>
 <div className='table-responsive'><table className='table bordered-table align-middle text-nowrap'><thead><tr><th>PAYMENT ID</th><th>REGISTRATION</th><th>APPLICANT / BUSINESS</th><th>PLAN</th><th>AMOUNT</th><th>MODE</th><th>STATUS</th><th>TRANSACTION</th><th>PAID AT</th><th>RECORDED BY</th><th>ACTIONS</th></tr></thead><tbody>{loading?<tr><td colSpan='11' className='text-center'>Loading...</td></tr>:!items.length?<tr><td colSpan='11' className='text-center'>No records found.</td></tr>:items.map((item)=><tr key={item.id}><td>{item.id.slice(0,8)}</td><td>{item.registrationId.slice(0,8)}</td><td>{item.applicantName||"—"}<div className='text-xs'>{item.businessName||""}</div></td><td>{item.planName||"—"}</td><td>{formatInr(item.amount)}</td><td>{item.paymentMode}</td><td><span className={`px-10 py-4 rounded-pill ${statusBadge(item.paymentStatus)}`}>{item.paymentStatus}</span></td><td>{item.transactionId||"—"}</td><td>{formatDate(item.paidAt)}</td><td>{item.recordedBy||"—"}</td><td><button className='btn btn-sm btn-outline-primary me-4' onClick={()=>setModal({mode:"view",item})}>View</button><button className='btn btn-sm btn-outline-success me-4' onClick={()=>setModal({mode:"edit",item})}>Edit</button>{item.paymentStatus==="pending"&&<button className='btn btn-sm btn-success me-4' onClick={()=>updateStatus(item,"success")}>Mark Paid</button>}{item.paymentStatus==="success"&&<button className='btn btn-sm btn-outline-danger' onClick={()=>updateStatus(item,"refunded")}>Refund</button>}</td></tr>)}</tbody></table></div>
 <div className='d-flex justify-content-between'><span>Showing {items.length?(page-1)*PAGE_SIZE+1:0}–{Math.min(page*PAGE_SIZE,total)} of {total}</span><div><button className='btn btn-sm btn-light me-4' disabled={page===1} onClick={()=>setPage(page-1)}>Previous</button><button className='btn btn-sm btn-light' disabled={page*PAGE_SIZE>=total} onClick={()=>setPage(page+1)}>Next</button></div></div>
 </div></div>{modal&&<FormModal size='lg' onClose={()=>setModal(null)}><FranchisePaymentFormLayer registrations={registrations} initialData={modal.item} isEdit={modal.mode==="edit"} isView={modal.mode==="view"} onCancel={()=>setModal(null)} onSuccess={()=>{setModal(null);load();}}/></FormModal>}</>;
}
const Card=({title,value})=><div className='col-md-3'><div className='card radius-12'><div className='card-body'><div className='text-secondary-light'>{title}</div><h4 className='mb-0 mt-8'>{value}</h4></div></div></div>;
