import React, { useCallback, useEffect, useState } from "react";
import { Icon } from "@iconify/react/dist/iconify.js";
import { toast } from "react-toastify";
import { approveFranchiseRegistration, deleteFranchiseRegistration, listFranchisePlans, listFranchiseRegistrations, rejectFranchiseRegistration } from "../../../lib/api/adminApi";
import { ApiError } from "../../../lib/api/client";
import FormModal from "../../../components/admin/FormModal";
import { exportCsv, formatDate, formatInr, PAGE_SIZE, statusBadge } from "../franchiseShared";
import FranchiseRegistrationFormLayer from "./FranchiseRegistrationFormLayer";

const tabs = ["pending", "under_review", "approved", "rejected", "all"];
export default function FranchiseRegistrationListLayer() {
  const [items,setItems]=useState([]),[plans,setPlans]=useState([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[status,setStatus]=useState("pending"),[planId,setPlanId]=useState(""),[q,setQ]=useState(""),[state,setState]=useState(""),[city,setCity]=useState(""),[loading,setLoading]=useState(true),[modal,setModal]=useState(null);
  const load=useCallback(async()=>{setLoading(true);try{const [result,planResult]=await Promise.all([listFranchiseRegistrations({status,planId:planId||undefined,q:q||undefined,state:state||undefined,city:city||undefined,limit:PAGE_SIZE,offset:(page-1)*PAGE_SIZE}),listFranchisePlans({includeInactive:true,limit:100,offset:0})]);setItems(result.items||[]);setTotal(result.total||0);setPlans(planResult.items||[]);}catch(error){toast.error(error instanceof ApiError?error.message:String(error));}finally{setLoading(false);}},[status,planId,q,state,city,page]);
  useEffect(()=>{load();},[load]);
  const approve=async(item)=>{if(!item.planId)return toast.error("Select a plan before approval.");if(!window.confirm("Approve this registration?"))return;try{const result=await approveFranchiseRegistration(item.id);toast.success(result.paymentRequired?"Approval recorded; payment is pending.":"Registration activated.");load();}catch(error){toast.error(error instanceof ApiError?error.message:String(error));}};
  const reject=async(item)=>{const reason=window.prompt("Rejection reason:");if(!reason)return;try{await rejectFranchiseRegistration(item.id,reason);toast.success("Registration rejected.");load();}catch(error){toast.error(error instanceof ApiError?error.message:String(error));}};
  const remove=async(item)=>{if(!window.confirm("Delete this registration?"))return;try{await deleteFranchiseRegistration(item.id);toast.success("Registration deleted.");load();}catch(error){toast.error(error instanceof ApiError?error.message:String(error));}};
  return <><div className='mb-20 d-flex justify-content-between align-items-start'><div><h3 className='fw-bold mb-4'>Franchise Registrations</h3><p className='text-secondary-light'>Manage franchise applications, payments, approvals, and conversions.</p></div><button className='btn btn-outline-primary' onClick={load}><Icon icon='mdi:refresh' /> Reconcile registrations</button></div>
    <div className='card radius-12 mb-20'><div className='card-body'><h5>Advanced search & filters</h5><div className='row g-12'><Field><select className='form-select' value={planId} onChange={(e)=>{setPlanId(e.target.value);setPage(1);}}><option value=''>All Plans</option>{plans.map((plan)=><option key={plan.id} value={plan.id}>{plan.planName}</option>)}</select></Field><Field><select className='form-select' value={status} onChange={(e)=>{setStatus(e.target.value);setPage(1);}}>{tabs.map((tab)=><option key={tab} value={tab}>{tab.replace("_"," ").replace(/\b\w/g,(x)=>x.toUpperCase())}</option>)}</select></Field><Field><input className='form-control' placeholder='Search state' value={state} onChange={(e)=>setState(e.target.value)} /></Field><Field><input className='form-control' placeholder='Search city' value={city} onChange={(e)=>setCity(e.target.value)} /></Field><Field><input className='form-control' placeholder='Mobile / Email / Name' value={q} onChange={(e)=>setQ(e.target.value)} /></Field></div></div></div>
    <div className='card radius-12'><div className='card-body p-24'><div className='d-flex justify-content-between gap-10 mb-20'><input className='form-control' style={{maxWidth:420}} placeholder='Search name, mobile, email...' value={q} onChange={(e)=>setQ(e.target.value)} /><div className='d-flex gap-8'><button className='btn btn-outline-secondary' onClick={()=>exportCsv("franchise-registrations",["ID","Applicant","Business","Plan","Amount","Status","Date"],items.map((x)=>[x.id,x.applicantName,x.businessName,x.planName,x.planAmount,x.status,x.createdAt]))}>CSV</button><button className='btn btn-primary' onClick={()=>setModal({mode:"add"})}><Icon icon='mdi:plus' /> Add Registration</button></div></div>
      <div className='table-responsive'><table className='table bordered-table align-middle text-nowrap'><thead><tr><th>ID</th><th>APPLICANT</th><th>BUSINESS</th><th>CONTACT</th><th>CITY / STATE</th><th>TERRITORY</th><th>PLAN</th><th>BUDGET</th><th>STATUS</th><th>APPLIED</th><th>ACTIONS</th></tr></thead><tbody>{loading?<tr><td colSpan='11' className='text-center'>Loading...</td></tr>:!items.length?<tr><td colSpan='11' className='text-center'>No registrations found.</td></tr>:items.map((item)=><tr key={item.id}><td title={item.id}>{item.id.slice(0,8)}</td><td><strong>{item.applicantName}</strong></td><td>{item.businessName||"—"}</td><td>{item.phone||"—"}<div className='text-xs'>{item.email||""}</div></td><td>{item.city||"—"} / {item.state||"—"}</td><td>{item.preferredTerritory||"—"}</td><td>{item.planName||"—"}</td><td>{formatInr(item.investmentBudget)}</td><td><span className={`px-10 py-4 rounded-pill ${statusBadge(item.status)}`}>{item.status.replace("_"," ")}</span></td><td>{formatDate(item.createdAt)}</td><td><button className='btn btn-sm btn-outline-primary me-4' onClick={()=>setModal({mode:"view",item})}>View</button><button className='btn btn-sm btn-outline-success me-4' onClick={()=>setModal({mode:"edit",item})}>Edit</button>{!["active","approved","rejected"].includes(item.status)&&<><button className='btn btn-sm btn-success me-4' onClick={()=>approve(item)}>Approve</button><button className='btn btn-sm btn-warning me-4' onClick={()=>reject(item)}>Reject</button></>}<button className='btn btn-sm btn-outline-danger' onClick={()=>remove(item)}>Delete</button></td></tr>)}</tbody></table></div>
      <div className='d-flex justify-content-between'><span>Showing {items.length?(page-1)*PAGE_SIZE+1:0}–{Math.min(page*PAGE_SIZE,total)} of {total}</span><div><button className='btn btn-sm btn-light me-4' disabled={page===1} onClick={()=>setPage(page-1)}>Previous</button><button className='btn btn-sm btn-light' disabled={page*PAGE_SIZE>=total} onClick={()=>setPage(page+1)}>Next</button></div></div>
    </div></div>{modal&&<FormModal size='xl' onClose={()=>setModal(null)}><FranchiseRegistrationFormLayer plans={plans} initialData={modal.item} isEdit={modal.mode==="edit"} isView={modal.mode==="view"} onCancel={()=>setModal(null)} onSuccess={()=>{setModal(null);load();}} /></FormModal>}</>;
}
const Field=({children})=><div className='col-md'>{children}</div>;
